import { AnyItemConfig } from './types'

export const CANVAS_ITEMS: AnyItemConfig[] = [
  // Word Cards — only the name
  {
    id: 'word-thinker',
    type: 'word-card',
    x: 50,
    y: 48,
    text: 'Roby Liebbe',
    fontSize: 34,
    color: '#ece8e1',
    italic: false,
    floatAmplitude: 5,
    floatSpeed: 3.7,
    floatPhaseOffset: 2.4,
    draggable: true,
  },
  // Tag Pills
  {
    id: 'tag-startups',
    type: 'tag-pill',
    x: 22,
    y: 38,
    text: '/ startups',
    floatAmplitude: 4,
    floatSpeed: 3.0,
    floatPhaseOffset: 1.5,
    draggable: true,
  },
  {
    id: 'tag-film',
    type: 'tag-pill',
    x: 88,
    y: 30,
    text: '/ film',
    floatAmplitude: 5,
    floatSpeed: 3.8,
    floatPhaseOffset: 0.3,
    draggable: true,
  },
  {
    id: 'tag-writing',
    type: 'tag-pill',
    x: 68,
    y: 85,
    text: '/ writing',
    floatAmplitude: 6,
    floatSpeed: 2.7,
    floatPhaseOffset: 2.0,
    draggable: true,
  },
  {
    id: 'tag-products',
    type: 'tag-pill',
    x: 30,
    y: 90,
    text: '/ products',
    floatAmplitude: 4,
    floatSpeed: 4.2,
    floatPhaseOffset: 1.8,
    draggable: true,
  },
  {
    id: 'tag-ideas',
    type: 'tag-pill',
    x: 12,
    y: 62,
    text: '/ ideas',
    floatAmplitude: 7,
    floatSpeed: 3.5,
    floatPhaseOffset: 0.6,
    draggable: true,
  },
  {
    id: 'tag-design',
    type: 'tag-pill',
    x: 82,
    y: 55,
    text: '/ design',
    floatAmplitude: 5,
    floatSpeed: 2.5,
    floatPhaseOffset: 2.7,
    draggable: true,
  },
  // Image Placeholders
  {
    id: 'img-1',
    type: 'image-placeholder',
    x: 9,
    y: 22,
    width: 150,
    height: 200,
    rotate: -4,
    floatAmplitude: 5,
    floatSpeed: 3.3,
    floatPhaseOffset: 1.0,
    draggable: true,
  },
  {
    id: 'img-2',
    type: 'image-placeholder',
    x: 76,
    y: 20,
    width: 180,
    height: 125,
    rotate: 3,
    floatAmplitude: 6,
    floatSpeed: 4.0,
    floatPhaseOffset: 2.2,
    draggable: true,
  },
  {
    id: 'img-3',
    type: 'image-placeholder',
    x: 84,
    y: 75,
    width: 130,
    height: 170,
    rotate: -2,
    floatAmplitude: 4,
    floatSpeed: 3.6,
    floatPhaseOffset: 0.4,
    draggable: true,
  },
  {
    id: 'img-4',
    type: 'image-placeholder',
    x: 16,
    y: 76,
    width: 140,
    height: 185,
    rotate: 2,
    floatAmplitude: 5,
    floatSpeed: 3.1,
    floatPhaseOffset: 1.8,
    draggable: true,
  },
  {
    id: 'img-5',
    type: 'image-placeholder',
    x: 50,
    y: 10,
    width: 200,
    height: 120,
    rotate: -1,
    floatAmplitude: 4,
    floatSpeed: 2.9,
    floatPhaseOffset: 0.7,
    draggable: true,
  },
  {
    id: 'img-6',
    type: 'image-placeholder',
    x: 38,
    y: 68,
    width: 120,
    height: 155,
    rotate: -3,
    floatAmplitude: 5,
    floatSpeed: 3.2,
    floatPhaseOffset: 1.4,
    draggable: true,
  },
  // Quote Fragments
  {
    id: 'quote-1',
    type: 'quote-fragment',
    x: 33,
    y: 25,
    text: '"built from scratch"',
    floatAmplitude: 5,
    floatSpeed: 3.1,
    floatPhaseOffset: 1.6,
    draggable: true,
  },
  {
    id: 'quote-2',
    type: 'quote-fragment',
    x: 35,
    y: 84,
    text: '"still figuring it out"',
    floatAmplitude: 7,
    floatSpeed: 4.3,
    floatPhaseOffset: 0.9,
    draggable: true,
  },
  {
    id: 'quote-3',
    type: 'quote-fragment',
    x: 70,
    y: 63,
    text: '"ships things"',
    floatAmplitude: 6,
    floatSpeed: 2.8,
    floatPhaseOffset: 2.5,
    draggable: true,
  },
  {
    id: 'quote-4',
    type: 'quote-fragment',
    x: 60,
    y: 38,
    text: '"Memento Mori"',
    floatAmplitude: 5,
    floatSpeed: 3.4,
    floatPhaseOffset: 1.1,
    draggable: true,
  },
  {
    id: 'quote-5',
    type: 'quote-fragment',
    x: 27,
    y: 55,
    text: '"make it count"',
    floatAmplitude: 6,
    floatSpeed: 3.9,
    floatPhaseOffset: 2.1,
    draggable: true,
  },
  {
    id: 'quote-6',
    type: 'quote-fragment',
    x: 55,
    y: 76,
    text: '"keep going"',
    floatAmplitude: 4,
    floatSpeed: 2.6,
    floatPhaseOffset: 0.3,
    draggable: true,
  },
  // Year Stamp
  {
    id: 'year-stamp',
    type: 'year-stamp',
    x: 50,
    y: 50,
    text: '2026',
    floatAmplitude: 0,
    floatSpeed: 1,
    floatPhaseOffset: 0,
    draggable: false,
  },
  // Status Dot
  {
    id: 'status-dot',
    type: 'status-dot',
    x: 50,
    y: 92,
    text: '● Available for interesting things',
    floatAmplitude: 3,
    floatSpeed: 2.0,
    floatPhaseOffset: 0.5,
    draggable: true,
  },
]
